apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-pod-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: app
          image: theerisnet/goorm-docker-spring:latest