name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment for the workflow'
        required: true
        default: 'Triggered by workflow_dispatch'

env:
#  S3_BUCKET_NAME: groom-tricount-bucket
#  DOCKER_TAG_VERSION: ${{ github.run_number }}
#  DESTINATION_FILE: groom-test-docker.tar
#  DESTINATION_LATEST_FILE: groom-test-docker-latest.tar
#  ZIP_FILE: groom-test-docker.zip
#  CODE_DEPLOY_NAME: groom-tricount-codedeploy
#  CODE_DEPLOY_GROUP_NAME: groom-tricount-codedeploy-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '8.7'

    - name: Build with Gradle 8.7
      run: gradle clean bootJar